### ISSUE TITLE
Team photos component on about page

### ISSUE THREAD

**Issue by MankiratSingh1315** [MicrosoftStudentChapter/makeathon6-website#23]
Photos of the Executive board and all the coordinators to be displayed in a good manner with name of every person.
Ideation required for UI if possible

**Comment by man0407** [comment]
working on UI

**Comment by man0407** [comment]
![image](https://github.com/MicrosoftStudentChapter/makeathon6-website/assets/149615815/34a684a2-a5fb-41c2-bb27-86a6c092f844)

**Comment by man0407** [comment]
PR generated
