### ISSUE TITLE
Correct Alignment for power sponser 

### ISSUE THREAD

**Issue by navdeepsingh112** [MicrosoftStudentChapter/makeathon6-website#50]

**Comment by akshatnathani** [comment]
![Screenshot 2024-02-02 235920](https://github.com/MicrosoftStudentChapter/makeathon6-website/assets/136986803/587632a7-9553-40df-9f94-98f3d436d628)
alignment is right in my device

**Comment by MankiratSingh1315** [comment]
okay it's working normally now
Thanks for letting us know
