### ISSUE TITLE
footer for phone view 

### ISSUE THREAD

**Issue by navdeepsingh112** [MicrosoftStudentChapter/makeathon6-website#51]
Instagram facebook and twitter logo is blurry ,
Correct responsiveness for the footer.

**Comment by JeevantVerma** [comment]
Ok, will look into this.

**Comment by JeevantVerma** [comment]
PR Generated.

**Comment by Siddharth-Agg-arwal** [comment]
Checked the footer and merged the PR for the same. Its responsive and works correctly for both mobile and desktop view. Good work Jeevant!
