### ISSUE TITLE
Navbar is Not clear and font is bad and on navbar on clicking on home or about blue background appears

### ISSUE THREAD

**Issue by navdeepsingh112** [MicrosoftStudentChapter/makeathon6-website#52]

**Comment by adityacodes30** [comment]
also navbar elements are not in center , give a gaussian blur overlay perhaps ?

**Comment by YuvanshPathak** [comment]
if the image is not clear then can try using this image... its much clearer
![wallpaperflare com_wallpaper cropped](https://github.com/MicrosoftStudentChapter/makeathon6-website/assets/149525378/b8a1b2b9-71b8-4ef0-89d7-ce246678d1a2)

**Comment by MankiratSingh1315** [comment]
> if the image is not clear then can try using this image... its much clearer ![wallpaperflare com_wallpaper cropped](https://private-user-images.githubusercontent.com/149525378/302019303-b8a1b2b9-71b8-4ef0-89d7-ce246678d1a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTU3OTIsIm5iZiI6MTcwNjk1NTQ5MiwicGF0aCI6Ii8xNDk1MjUzNzgvMzAyMDE5MzAzLWI4YTFiMmI5LTcxYjgtNGVmMC04OWQ3LWNlMjQ2Njc4ZDFhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QxMDE4MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTkwNzE4ZmE4ZmFjYjBmNDZmYWY3Nzc2MDEyYWM5ZDJkYmU4NmRkN2I0MmRhM2QwMWEzYzIzNzhiZDE0YWM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z3AipGYu9XxwcTpGVwL10IE3Ygh-UfhKdKhLMc60btc)

Basically the user can't distinguish that the dragon icon is navbar or not
Try giving some shake animation or some glow effect to it so that it become obvious that it's clickable
