### ISSUE TITLE
Sponsors page is hardcoded, [code betterment]

### ISSUE THREAD

**Issue by adityacodes30** [MicrosoftStudentChapter/makeathon6-website#56]
make it so that data is taken from an array , and elements are rendered using a map function , create 3 data arrays with dummy data , use props and make everything dynamic

**Comment by vaibhavi4246** [comment]
I will be working on this

**Comment by SanyamWadhwa07** [comment]
I will be working on this

**Comment by akshatnathani** [comment]
I'll be working on this

**Comment by MankiratSingh1315** [comment]
is this completed?
@adityacodes30

**Comment by vaibhavi4246** [comment]
Yes
