### ISSUE TITLE
Style fixes for the pop up modal 

### ISSUE THREAD

**Issue by adityacodes30** [MicrosoftStudentChapter/makeathon6-website#6]
<img width="1456" alt="image" src="https://github.com/MicrosoftStudentChapter/makeathon6-website/assets/110766802/dfc9d5cf-4d33-4295-97a4-977f81ee2096">

The text looks very cramped and collides with the close button , overall , there needs to be some spacing in the headings and paragraphs . Font sizing could also see some tweaks . Overall just make the modal aesthetically pleasing and in flow

**Comment by JeevantVerma** [comment]
I'll look into this one.

**Comment by JeevantVerma** [comment]
I've made the pull request for the issue fix on the tracks branch Bhaiya.

**Comment by adityacodes30** [comment]
merged

**Comment by adityacodes30** [comment]
issue resolved
