### ISSUE TITLE
Tracks page hover animation too abrupt

### ISSUE THREAD

**Issue by adityacodes30** [MicrosoftStudentChapter/makeathon6-website#7]
add a nice cubic bezier / increase time of animation , decrease the on hover zoom + shadow by about 20%

**Comment by Ishita-01** [comment]
I will look into this

**Comment by adityacodes30** [comment]
assigned , please complete by 4pm 27th

**Comment by Ishita-01** [comment]
Pull request generated for this issue.

**Comment by adityacodes30** [comment]
merged
